name : 'Bump Version In Dependants'
description: 'This action bumps version of your Node.js package in its dependants'
inputs:
  github_token:
    description: 'Token to use GitHub API.'
    required: true
  package:
    description: 'Name of a node.js package required for bump'
    required: true
  user:
    description: 'Information about the authenticated user'
    required: false
  org:
    description: 'Organization of the authenticated user'
    required: false
  ignore:
    description: 'List of paths to package.json that should be ignored'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'link'
  color: 'blue'